### ISSUE TITLE
Any idea what is happening here?

### ISSUE THREAD

**Issue by MartinJRS** [Place1/homebridge-tradfri-gateway#1]
[07/02/2022, 12:58:33] Error: failed to connect: Error: EACCES: permission denied, open '/usr/local/lib/node_modules/homebridge-tradfri-gateway/build/.credentials.cache'
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge-tradfri-gateway/src/tradfri-client.ts:48:11)
    at step (/usr/local/lib/node_modules/homebridge-tradfri-gateway/build/tradfri-client.js:52:23)
    at Object.throw (/usr/local/lib/node_modules/homebridge-tradfri-gateway/build/tradfri-client.js:33:53)
    at rejected (/usr/local/lib/node_modules/homebridge-tradfri-gateway/build/tradfri-client.js:25:65)

**Comment by MartinJRS** [comment]
Well, looks like this plugin is dead 😵
